FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/build ./build
EXPOSE 3000
ENV PORT=3000
ENV NODE_ENV=production
CMD ["node", "build"]
